sudo: required
services:
  - docker

before_install:
  - docker build -t luanrubensf/complex-fibonacci-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run luanrubensf/complex-fibonacci-test npm test -- --coverage

after_success:
  - docker build -t luanrubens/cfc-client ./client
  - docker build -t luanrubens/cfc-nginx ./nginx
  - docker build -t luanrubens/cfc-server ./server
  - docker build -t luanrubens/cfc-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push luanrubens/cfc-client
  - docker push luanrubens/cfc-nginx
  - docker push luanrubens/cfc-server
  - docker push luanrubens/cfc-worker
