sudo: required
services:
  - docker

before_install:
  - docker build -t luanrubensf/complex-fibonacci-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run luanrubensf/complex-fibonacci-test npm test -- --coverage

after_success:
  - docker build -t luanrubensf/cfc-client ./client
  - docker build -t luanrubensf/cfc-nginx ./nginx
  - docker build -t luanrubensf/cfc-server ./server
  - docker build -t luanrubensf/cfc-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push luanrubensf/cfc-client
  - docker push luanrubensf/cfc-nginx
  - docker push luanrubensf/cfc-server
  - docker push luanrubensf/cfc-worker

deploy:
  provider: elasticbeanstalk
  region: sa-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-sa-east-1-246025812221
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
    